# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        key: ${{secrets.REMOTE_SERVER_SSH}}
        host: ${{secrets.REMOTE_SERVER_IP}}
        username: ${{secrets.REMOTE_SERVER_USER}}
        script: |
          pm2 delete all
          cd /var/www/html/api.alejandria.edu.mx/api-cea-jpg
          git pull
          npm install
          pm2 start index.js --name api_cea
        
        
